spring.application.name=sistema-pedidos

spring.h2.console.enabled=true
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/freepdb1
spring.datasource.username=pedidos
spring.datasource.password=pedidos123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
