
--CREATE de todas las tablas

CREATE TABLE USUARIO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    USERNAME VARCHAR(50) UNIQUE,
    PASSWORD VARCHAR(255)
);

CREATE TABLE CARRITO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT,
    CODIGO VARCHAR(50) UNIQUE,
    CONSTRAINT FK_CARRITO_USUARIO
        FOREIGN KEY (USUARIO_ID)
        REFERENCES USUARIO(ID)
);

CREATE TABLE CATEGORIA(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255)
);

CREATE TABLE DESCUENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA_ID INT,
    PORCENTAJE DECIMAL(5,2),
    CONSTRAINT FK_DESCUENTO_CATEGORIA
        FOREIGN KEY (CATEGORIA_ID)
        REFERENCES CATEGORIA(ID)
);

CREATE TABLE PRODUCTO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    VERSION BIGINT DEFAULT 0,
    NOMBRE VARCHAR (255),
    PRECIO DECIMAL(10,2),
    STOCK  INT,
    CODIGO VARCHAR(50) UNIQUE,
    CATEGORIA_ID INT,
    CONSTRAINT FK_PRODUCTO_CATEGORIA
        FOREIGN KEY (CATEGORIA_ID)
        REFERENCES CATEGORIA(ID)
);

CREATE TABLE CARRITO_ITEM(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CARRITO_ID INT,
    PRODUCTO_ID INT,
    CANTIDAD INT,

    CONSTRAINT FK_CARRITO_CARRITO_ITEM
        FOREIGN KEY (CARRITO_ID)
        REFERENCES CARRITO(ID),

    CONSTRAINT FK_PRODUCTO_CARRITO_ITEM
        FOREIGN KEY (PRODUCTO_ID)
        REFERENCES PRODUCTO(ID),

    CONSTRAINT UK_CARRITO_PRODUCTO UNIQUE(CARRITO_ID, PRODUCTO_ID)
);

CREATE TABLE PEDIDO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT,
    CARRITO_ID INT,
    PRECIO_FINAL DECIMAL(10,2),
    ESTADO VARCHAR(50),
    FECHA TIMESTAMP,
    MENSAJE_ERROR VARCHAR(255),

    CONSTRAINT FK_PEDIDO_USUARIO
        FOREIGN KEY (USUARIO_ID)
        REFERENCES USUARIO(ID),

    CONSTRAINT FK_PEDIDO_CARRITO
        FOREIGN KEY (CARRITO_ID)
        REFERENCES CARRITO(ID)
);

--INSERT de valores en cada tabla

INSERT INTO USUARIO (NOMBRE, APELLIDO, USERNAME, PASSWORD)
VALUES ('Admin', 'Root', 'admin', '$2a$10$HGw2pt2lyyNo.Q7mP831.uBJTy9MwN.ejJ7P.sBs7ugjb34YU/Pwy');

INSERT INTO CATEGORIA (NOMBRE) VALUES
('TECNOLOGIA'), --1
('INDUMENTARIA'), --2
('HOGAR'), --3
('ALIMENTOS'), --4
('ENTRETENIMIENTO'); --5

INSERT INTO PRODUCTO (VERSION, NOMBRE, PRECIO, STOCK, CODIGO, CATEGORIA_ID) VALUES
-- TECNOLOGIA (1)
(0, 'Mouse Logitech', 1500.00, 3, 'TEC-001', 1),
(0, 'Teclado Redragon', 3500.00, 5, 'TEC-002', 1),
(0, 'Auriculares Sony', 12000.00, 3, 'TEC-003', 1),

-- INDUMENTARIA (2)
(0, 'Remera Nike', 8000.00, 10, 'IND-001', 2),
(0, 'Zapatillas Adidas', 25000.00, 11, 'IND-002', 2),
(0, 'Campera Puma', 18000.00, 4, 'IND-003', 2),

-- HOGAR (3)
(0, 'Silla de comedor', 22000.00, 2, 'HOG-001', 3),
(0, 'Lampara LED', 5000.00, 3, 'HOG-002', 3),
(0, 'Mesa de madera', 45000.00, 4, 'HOG-003', 3),

-- ALIMENTOS (4)
(0, 'Coca Cola 2L', 2500.00, 22, 'ALI-001', 4),
(0, 'Galletitas Oreo', 1200.00, 12, 'ALI-002', 4),
(0, 'Pizza congelada', 3000.00, 4, 'ALI-003', 4),

-- ENTRETENIMIENTO (5)
(0, 'PlayStation 5', 900000.00, 3, 'ENT-001', 5),
(0, 'Juego FIFA 24', 60000.00, 4, 'ENT-002', 5),
(0, 'Control PS5', 85000.00, 3, 'ENT-003', 5);

INSERT INTO DESCUENTO (CATEGORIA_ID, PORCENTAJE) VALUES
(1, 10.00),  -- TECNOLOGIA → 10%
(2, 15.00),  -- INDUMENTARIA → 15%
(4, 2.50);   -- ALIMENTOS → 2.5%